import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "MuggleLink",
  description: "Created by MugglePay",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 3be9180b37d8bc6019b0a2c817b6db4fa071ee94
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={cn(inter.className, 'gradient-background')}>{children}</body>


    </html>
  );
}
